/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#39000d",
        "on-tertiary-container": "#570018",
        "on-primary": "#47007c",
        "secondary": "#53ddfc",
        "on-primary-container": "#360061",
        "secondary-container": "#00687a",
        "on-error-container": "#ffb2b9",
        "tertiary": "#ff95a0",
        "outline": "#777575",
        "error": "#ff6e84",
        "surface-dim": "#0e0e0e",
        "primary-dim": "#9c48ea",
        "tertiary-dim": "#f47786",
        "on-surface-variant": "#adaaaa",
        "on-secondary-fixed": "#003a45",
        "surface-container-high": "#201f1f",
        "surface-container-highest": "#262626",
        "on-secondary": "#004b58",
        "surface": "#0e0e0e",
        "tertiary-container": "#fe7e8e",
        "inverse-primary": "#842cd3",
        "primary-fixed-dim": "#b971ff",
        "on-primary-fixed": "#000000",
        "on-secondary-container": "#ecfaff",
        "on-background": "#ffffff",
        "surface-container-lowest": "#000000",
        "secondary-fixed": "#65e1ff",
        "primary": "#cc97ff",
        "on-tertiary": "#680921",
        "tertiary-fixed": "#ff909c",
        "error-container": "#a70138",
        "background": "#0e0e0e",
        "on-tertiary-fixed-variant": "#711227",
        "on-error": "#490013",
        "tertiary-fixed-dim": "#fa7c8b",
        "secondary-dim": "#40ceed",
        "inverse-surface": "#fcf8f8",
        "surface-container": "#1a1919",
        "surface-tint": "#cc97ff",
        "on-primary-fixed-variant": "#430076",
        "surface-container-low": "#131313",
        "error-dim": "#d73357",
        "primary-container": "#c284ff",
        "outline-variant": "#494847",
        "primary-fixed": "#c284ff",
        "on-surface": "#ffffff",
        "inverse-on-surface": "#565554",
        "surface-variant": "#262626",
        "on-secondary-fixed-variant": "#005969",
        "surface-bright": "#2c2c2c",
        "secondary-fixed-dim": "#48d4f3"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "display": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
